version: '3.8'
services:

  db:
    image: postgres
    environment:
      POSTGRES_DB: aitrain
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aitrainPass
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: juliodaza/aitrain-backend:0.1.3
    ports:
      - "3900:3900"
    environment:
      DATABASE_URL: "postgresql://postgres:aitrainPass@db:5432/aitrain?schema=public"
    depends_on:
      - db

volumes:
  postgres_data: